defaults:
    model: "models/text-bison-001"
    temperature: 0.7
    candidate_count: 1
    top_k: 40
    top_p: 0.95
    max_output_tokens: 1024
    stop_sequences: []
    safety_settings: [
        {"category": "HARM_CATEGORY_DEROGATORY", "threshold": 4},
        {"category": "HARM_CATEGORY_TOXICITY", "threshold": 4},
        {"category": "HARM_CATEGORY_VIOLENCE", "threshold": 4},
        {"category": "HARM_CATEGORY_SEXUAL", "threshold": 4},
        {"category": "HARM_CATEGORY_MEDICAL", "threshold": 4},
        {"category": "HARM_CATEGORY_DANGEROUS", "threshold": 4},
    ]
context: "You are a content creation helper who helps to turn technical concepts into short text easier to understand.\nExplain the following concept in a short text format, and give some examples:"